version: '3'
services:
  odoo:
    container_name: odoo
    image: odoo:8
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons/:rw
      - ./config/odoo:/etc/odoo/:rw
      - ./odoo-web-data:/var/lib/odoo/:rw
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    ports:
      - "8069:8069"
    depends_on:
      - "db"
    networks:
      - odoo_network
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
        - 80:80
    volumes:
        - ./config/nginx/conf:/etc/nginx/conf.d/:rw
    depends_on:
        - "odoo"
    networks:
        - odoo_network
  sshtunnel:
    image: binlab/sshtunnel
    container_name: sshtunnel
    hostname: sshtunnel
    restart: unless-stopped
    command: |
      -R *:80:nginx:80
      root@app.manzada.net
    volumes:
        - ./.public_server.pem:/sshtunnel_rsa:ro
    depends_on:
        - nginx
    networks:
        - odoo_network
  db:
    container_name: postgresql
    image: postgres:13
    restart: always
    command: -c config_file=/etc/postgresql.conf
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./customPostgresql.conf:/etc/postgresql.conf
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      - odoo_network
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"

networks:
  odoo_network:
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
