services:
  odoo:
    container_name: odoo
    image: odoo:8
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    networks:
      - odoo_network
  db:
    image: postgres:13
    restart: always
    container_name: postgresql
    command: -c config_file=/etc/postgresql.conf
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./customPostgresql.conf:/etc/postgresql.conf
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - odoo_network
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"

networks:
  odoo_network:
    driver: bridge
    
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
